name: 'Branch Exists'
description: 'Check if a branch exists'
inputs:
  repository:
    description: 'Repo name'
    required: true
  branch:
    description: 'Branch name'
    required: true
  token:
    description: 'GitHub token'
    required: true
outputs:
  exists: # id of output
    description: 'Whether the branch exists or not (true/false)'
runs:
  using: 'node12'
  main: 'index.js'